### ISSUE TITLE
Got an error during the socket creation

### ISSUE THREAD

**Issue by franrios** [jsdario/udpc#1]
![image](https://cloud.githubusercontent.com/assets/7302131/16050525/471e506a-325c-11e6-89a4-23ec13587877.png)

**Comment by jsdario** [comment]
Solved! https://github.com/jsdario/udpc/commit/6d5d237acd94cfde8941af1d8db3c56efe7ba385

**Comment by franrios** [comment]
Thanks @jsdario!
